Update compile to use pre installated node.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -153,31 +153,31 @@ fi
 # Query node for its own path. As long as the Meteor version we got from
 # install.meteor.com is >=1.3, "meteor node" is available, even if the target
 # release predates that feature.
-METEOR_NODE=`METEOR node -e "process.stdout.write(process.execPath)"`
+#METEOR_NODE=`METEOR node -e "process.stdout.write(process.execPath)"`
 # Assume npm is in the same dir as node.
-METEOR_NPM="`dirname "$METEOR_NODE"`/npm"
+#METEOR_NPM="`dirname "$METEOR_NODE"`/npm"
 
-if [ -z "$METEOR_NPM" ] || [ -z "$METEOR_NODE" ] ; then
-  echo "FATAL: Can't find npm/node within meteor bundle. This is a bug. Please open an issue at https://github.com/AdmitHub/meteor-buildpack-horse.";
-  exit 1
-fi
+#if [ -z "$METEOR_NPM" ] || [ -z "$METEOR_NODE" ] ; then
+#  echo "FATAL: Can't find npm/node within meteor bundle. This is a bug. Please open an issue at https://github.com/AdmitHub/meteor-buildpack-horse.";
+#  exit 1
+#fi
 
 # Copy node into place for production.
-NODE="$COMPILE_DIR"/bin/node
-cp "$METEOR_NODE" "$NODE"
-chmod a+x "$NODE"
+#NODE="$COMPILE_DIR"/bin/node
+#cp "$METEOR_NODE" "$NODE"
+#chmod a+x "$NODE"
 
 # Add npm and node path so that 1.4's npm-rebuild.js will function.
-PATH="$METEOR_DIR/.meteor:`dirname $METEOR_NPM`:$COMPILE_DIR/bin:$PATH"
+#PATH="$METEOR_DIR/.meteor:`dirname $METEOR_NPM`:$COMPILE_DIR/bin:$PATH"
 
-echo "-----> Using node: `$NODE --version`"
-echo "----->    and npm: `$METEOR_NPM --version`"
+#echo "-----> Using node: `$NODE --version`"
+#echo "----->    and npm: `$METEOR_NPM --version`"
 
 # If we use npm on root, run npm install.  Don't use `--production` here, as we
 # may need devDependencies (e.g. webpack) in order to build the meteor app.
-if [ -e "$APP_SOURCE_DIR"/package.json ]; then
-  $METEOR_NPM install
-fi
+#if [ -e "$APP_SOURCE_DIR"/package.json ]; then
+#  $METEOR_NPM install
+#fi
 
 # Related to https://github.com/meteor/meteor/issues/2796 and
 # https://github.com/meteor/meteor/issues/2606.  Some packages only build their
@@ -208,7 +208,7 @@ rmdir $BUNDLE_DEST
 echo "-----> Installing npm production dependencies on built slug"
 if [ -e "$COMPILE_DIR"/app/programs/server/package.json ]; then
   cd "$COMPILE_DIR"/app/programs/server
-  $METEOR_NPM install --production
+  npm install --production
   cd "$APP_SOURCE_DIR"
 fi
 
@@ -216,13 +216,13 @@ fi
 # Environment
 #
 # Add an export of PATH which includes our compile dir, etc.
-echo "-----> Adding PATH environment"
-mkdir -p "$APP_CHECKOUT_DIR"/.profile.d
-cat > "$APP_CHECKOUT_DIR"/.profile.d/path.sh <<EOF
+#echo "-----> Adding PATH environment"
+#mkdir -p "$APP_CHECKOUT_DIR"/.profile.d
+#cat > "$APP_CHECKOUT_DIR"/.profile.d/path.sh <<EOF
   #!/bin/sh
-  export PATH=\$HOME/$COMPILE_DIR_SUFFIX/bin:\$PATH
-  export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:\$HOME/$COMPILE_DIR_SUFFIX/lib
-EOF
+#  export PATH=\$HOME/$COMPILE_DIR_SUFFIX/bin:\$PATH
+#  export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:\$HOME/$COMPILE_DIR_SUFFIX/lib
+#EOF
 
 #
 # Extras
@@ -230,15 +230,15 @@ EOF
 
 # source scripts in 'extra' dir, if any.  Create them for custom stuff like
 # binary dependencies, additional environment settings, etc.
-echo "-----> Running extras"
-for file in `ls "$BUILDPACK_DIR"/extra | sort`; do
-  . "$BUILDPACK_DIR"/extra/$file
-done
+#echo "-----> Running extras"
+#for file in `ls "$BUILDPACK_DIR"/extra | sort`; do
+#  . "$BUILDPACK_DIR"/extra/$file
+#done
 
 #
 # Clear cache after build is done
 #
-if [ -n "${BUILDPACK_CLEAR_CACHE+1}" ]; then
-  echo "-----> Clearing cache dir."
-  rm -rf $METEOR_DIR
-fi
+#if [ -n "${BUILDPACK_CLEAR_CACHE+1}" ]; then
+#  echo "-----> Clearing cache dir."
+#  rm -rf $METEOR_DIR
+#fi
